name: Go Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  TEST_MONGODB_URI: mongodb://localhost
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: MongoDB in GitHub Actions
      # You may pin to the exact commit or the version.
      # uses: supercharge/mongodb-github-action@e815fd8a9dfede09fd6e6c144f2c9f4875e933df
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        # MongoDB db to create (default: none)
        mongodb-db: envelope
        
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
